// cesi-premium/src/components/Footer.tsx
'use client';

import Link from 'next/link';
import Image from 'next/image';
import { useTheme } from 'next-themes';
import { useEffect, useState } from 'react';

export default function Footer() {
    const { resolvedTheme } = useTheme();
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
    }, []);
    return (
        <footer className="border-t border-border py-12 bg-surface/40 relative overflow-hidden">
            <div className="container mx-auto px-4 sm:px-6 flex flex-col md:flex-row justify-between items-center gap-6 max-w-7xl relative z-10">
                <div className="flex flex-col sm:flex-row items-center gap-4">
                    <Link href="/" className="relative h-8 w-40 block">
                        <Image
                            src={mounted && resolvedTheme === 'light' ? "/img/logo-black.svg" : "/img/logo.svg"}
                            alt="Kompas | CESI"
                            width={160}
                            height={32}
                            className="h-full w-auto object-contain"
                        />
                    </Link>
                </div>

                <p className="text-text-secondary text-xs text-center font-normal">
                    © {new Date().getFullYear()} Kompas | CESI. Développé par les étudiants, pour les étudiants.
                </p>

                <div className="flex flex-wrap items-center justify-center gap-5 text-xs font-medium">
                    <Link href="/cctl" className="text-text-secondary hover:text-text-primary transition-colors">
                        CCTL
                    </Link>
                    <Link href="/prosits" className="text-text-secondary hover:text-text-primary transition-colors">
                        Prosits
                    </Link>
                    <Link href="/livrables" className="text-text-secondary hover:text-text-primary transition-colors">
                        Livrables
                    </Link>
                    <Link href="/privacy" className="text-text-secondary hover:text-text-primary transition-colors">
                        Confidentialité
                    </Link>
                    <Link href="/terms" className="text-text-secondary hover:text-text-primary transition-colors">
                        Conditions & Éthique
                    </Link>
                </div>
            </div>
        </footer>
    );
}

// event-booking-platform/components/Footer.vue
<script setup lang="ts">

</script>

<template>

    <div class="rounded-lg shadow bg-neutral-950 m-4">
      <div class="w-full max-w-screen-xl mx-auto p-4 md:py-8">
        <div class="sm:flex sm:items-center sm:justify-between">
          <nuxt-link href="/" class="flex items-center mb-4 sm:mb-0 space-x-3 rtl:space-x-reverse bg-black p-4 rounded-2xl">
            <nuxt-img src="/img/logo.webp" loading="lazy" class="h-8" alt="F*cking world" width="32" height="32" />
          </nuxt-link>
          <ul class="flex flex-wrap items-center mb-6 font-medium sm:mb-0 text-neutral-400">
            <li>
              <nuxt-link to="/" class="hover:underline me-4 md:me-6">Accueil</nuxt-link>
            </li>
            <li>
              <nuxt-link to="/concept" class="hover:underline me-4 md:me-6">Concept</nuxt-link>
            </li>
            <li>
              <nuxt-link to="/dress-code" class="hover:underline me-4 md:me-6">Dress code</nuxt-link>
            </li>
            <li>
              <nuxt-link to="/reservation" class="hover:underline me-4 md:me-6">Réservation</nuxt-link>
            </li>
          </ul>
        </div>
        <hr class="my-6 sm:mx-auto border-neutral-700 lg:my-8" />
        <span class="block text-sm sm:text-center text-neutral-400">© 2025 <nuxt-link to="/" class="hover:underline">F*cking World</nuxt-link>. Tous droits réservés. Site web crée par le <nuxt-link to="https://osalys.studio" class="hover:underline">Studio Osalys</nuxt-link>.</span>
      </div>
    </div>

</template>

<style scoped>

</style>
